### PR TITLE
[NRTM] openxml+reflection+attributes demo

### PR DESCRIPTION
**Pull request by chenghuang-mdsol**
for demo

### CODE REVIEW

**Comment by chenghuang-mdsol** [comment]
@art2003 @junshao

**Comment by junshao** [comment]
As team discussion, needs to do following improvements:
- Remove attributes.
- ViewModel classes from inheriting interface to wrappers of interfaces (constructor parameter is interface).
- Remove `Excel2003Schema.Xml`.

**Comment by chenghuang-mdsol** [comment]
added the missing file.
Will do the refactor as @junshao metioned.
@art2003

**Comment by chenghuang-mdsol** [comment]
refactored a bit

**Comment by chenghuang-mdsol** [comment]
Close this one and will send another one which is rebased with @junshao 's code

**Pull request closed without merging**
